# Generated by Django 6.0.7 on 2026-07-23 03:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(help_text='ISO 4217 currency code (e.g. GHS, NGN)', max_length=3)),
                ('balance', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12)),
                ('reserved', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('purchase_credit', 'Purchase Credit'), ('promotional_credit', 'Promotional Credit'), ('usage_reservation', 'Usage Reservation'), ('usage_capture', 'Usage Capture'), ('reservation_release', 'Reservation Release'), ('refund', 'Refund'), ('expiration', 'Expiration'), ('administrative_correction', 'Administrative Correction')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive; effect on wallet depends on entry_type.', max_digits=12)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Globally unique — exactly-once guarantee.', max_length=255, unique=True)),
                ('reference', models.JSONField(default=dict, help_text="e.g. {'invocation_id': '...', 'payment_ref': '...'}")),
                ('reason', models.CharField(blank=True, help_text='Required for administrative_correction entries.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='credits.creditwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
