# Generated by Django 6.0.7 on 2026-07-23 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text="e.g. 'GH₵10 Top-up'", max_length=100)),
                ('currency', models.CharField(help_text='ISO 4217', max_length=3)),
                ('amount_credits', models.DecimalField(decimal_places=2, help_text='Wallet credits granted after successful payment.', max_digits=12)),
                ('price_minor_units', models.IntegerField(help_text='Price in kobo/pesewas/cents, e.g. 1000 = GH₵10.00')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, help_text='Immutable reference generated before calling Paystack.', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('currency', models.CharField(max_length=3)),
                ('amount_minor_units', models.IntegerField(help_text='Snapshot of pack price at purchase time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('credit_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='billing.creditpack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paystack_reference', models.CharField(blank=True, help_text="Paystack's transaction reference.", max_length=64)),
                ('paystack_status', models.CharField(blank=True, max_length=30)),
                ('raw_webhook_payload', models.JSONField(default=dict, help_text='Full webhook body for audit trail.')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='billing.purchase')),
            ],
        ),
    ]
