# Generated by Django 6.0.7 on 2026-07-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
