# Generated by Django 6.0.7 on 2026-07-23 13:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapabilityRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text="Wire value, e.g. 'fast', 'deepseek-pro', 'qwen-max'.", unique=True)),
                ('label', models.CharField(help_text="User-facing label, e.g. 'DeepSeek Pro (Reasoning)'.", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Short description shown in the capability selector.', max_length=500)),
                ('provider_key', models.CharField(choices=[('stub', 'Stub (Dev/Testing)'), ('deepseek', 'DeepSeek'), ('qwen', 'Qwen (Alibaba)')], help_text='Which adapter class to instantiate.', max_length=20)),
                ('upstream_model', models.CharField(help_text="Exact model id sent to the provider API, e.g. 'deepseek-v4-pro'.", max_length=100)),
                ('credit_rate_input', models.DecimalField(decimal_places=4, default=0, help_text='Retail credits per 1K input tokens (includes margin).', max_digits=10)),
                ('credit_rate_output', models.DecimalField(decimal_places=4, default=0, help_text='Retail credits per 1K output tokens (includes margin).', max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='If False, this route is invisible and unusable — the kill-switch.')),
                ('is_default', models.BooleanField(default=False, help_text='Exactly one active route should be the default selection.')),
                ('sort_order', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
    ]
