# Generated by Django 6.0.7 on 2026-07-23 13:56

from decimal import Decimal

from django.db import migrations


def seed_capability_routes(apps, schema_editor):
    CapabilityRoute = apps.get_model("providers", "CapabilityRoute")

    routes = [
        {
            "slug": "fast",
            "label": "Fast",
            "description": "Quick responses for everyday tasks (dev stub).",
            "provider_key": "stub",
            "upstream_model": "stub",
            "credit_rate_input": Decimal("0.0001"),
            "credit_rate_output": Decimal("0.0003"),
            "is_active": True,
            "is_default": True,
            "sort_order": 1,
        },
        {
            "slug": "deepseek-flash",
            "label": "DeepSeek Flash",
            "description": "Economical, fast responses.",
            "provider_key": "deepseek",
            "upstream_model": "deepseek-v4-flash",
            "credit_rate_input": Decimal("0.0500"),
            "credit_rate_output": Decimal("0.1500"),
            "is_active": False,  # inactive until API key is set
            "is_default": False,
            "sort_order": 10,
        },
        {
            "slug": "deepseek-pro",
            "label": "DeepSeek Pro (Reasoning)",
            "description": "Advanced reasoning for complex analysis.",
            "provider_key": "deepseek",
            "upstream_model": "deepseek-v4-pro",
            "credit_rate_input": Decimal("0.1500"),
            "credit_rate_output": Decimal("0.4500"),
            "is_active": False,
            "is_default": False,
            "sort_order": 20,
        },
        {
            "slug": "qwen-turbo",
            "label": "Qwen Turbo",
            "description": "Economy model for everyday tasks.",
            "provider_key": "qwen",
            "upstream_model": "qwen-turbo",
            "credit_rate_input": Decimal("0.0400"),
            "credit_rate_output": Decimal("0.1200"),
            "is_active": False,
            "is_default": False,
            "sort_order": 30,
        },
        {
            "slug": "qwen-plus",
            "label": "Qwen3 Plus",
            "description": "Everyday advanced model.",
            "provider_key": "qwen",
            "upstream_model": "qwen3-plus",
            "credit_rate_input": Decimal("0.0800"),
            "credit_rate_output": Decimal("0.2400"),
            "is_active": False,
            "is_default": False,
            "sort_order": 40,
        },
        {
            "slug": "qwen-max",
            "label": "Qwen3 Max (Reasoning)",
            "description": "Flagship reasoning model.",
            "provider_key": "qwen",
            "upstream_model": "qwen3-max",
            "credit_rate_input": Decimal("0.2000"),
            "credit_rate_output": Decimal("0.6000"),
            "is_active": False,
            "is_default": False,
            "sort_order": 50,
        },
    ]

    for route in routes:
        CapabilityRoute.objects.get_or_create(slug=route["slug"], defaults=route)


def remove_seed_routes(apps, schema_editor):
    CapabilityRoute = apps.get_model("providers", "CapabilityRoute")
    CapabilityRoute.objects.filter(
        slug__in=["fast", "deepseek-flash", "deepseek-pro", "qwen-turbo", "qwen-plus", "qwen-max"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_capability_routes, remove_seed_routes),
    ]
