# Generated by Django 6.0.7 on 2026-07-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_seed_capability_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='capabilityroute',
            name='provider_cost_input',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Wholesale USD per 1K input tokens (what we pay DeepSeek/Qwen).', max_digits=10),
        ),
        migrations.AddField(
            model_name='capabilityroute',
            name='provider_cost_output',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Wholesale USD per 1K output tokens (what we pay DeepSeek/Qwen).', max_digits=10),
        ),
    ]
