# Generated by Django 6.0.7 on 2026-07-23 14:59

from decimal import Decimal

from django.db import migrations

# DeepSeek pricing (per 1K tokens, USD):
#   deepseek-v4-flash: $0.14 input / $0.28 output
#   deepseek-v4-pro:  $0.435 input / $0.87 output
# Qwen pricing (per 1K tokens, USD):
#   qwen-turbo: $0.50 input / $1.50 output (approx)
#   qwen3-plus: $2.00 input / $6.00 output (approx)
#   qwen3-max:  $4.00 input / $16.00 output (approx)
# Stub: $0.00 / $0.00 (no real spend)

BACKFILL = {
    "fast": (Decimal("0.0"), Decimal("0.0")),
    "deepseek-flash": (Decimal("0.140"), Decimal("0.280")),
    "deepseek-pro": (Decimal("0.435"), Decimal("0.870")),
    "qwen-turbo": (Decimal("0.500"), Decimal("1.500")),
    "qwen-plus": (Decimal("2.000"), Decimal("6.000")),
    "qwen-max": (Decimal("4.000"), Decimal("16.000")),
}


def backfill_costs(apps, schema_editor):
    CapabilityRoute = apps.get_model("providers", "CapabilityRoute")
    for slug, (cost_in, cost_out) in BACKFILL.items():
        CapabilityRoute.objects.filter(slug=slug).update(
            provider_cost_input=cost_in,
            provider_cost_output=cost_out,
        )


def reverse_backfill(apps, schema_editor):
    CapabilityRoute = apps.get_model("providers", "CapabilityRoute")
    CapabilityRoute.objects.filter(slug__in=BACKFILL.keys()).update(
        provider_cost_input=Decimal("0.0"),
        provider_cost_output=Decimal("0.0"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0003_capabilityroute_provider_cost_input_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_costs, reverse_backfill),
    ]
