# Generated by Django 6.0.7 on 2026-07-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_fix_qwen_provider_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capabilityroute',
            name='provider_key',
            field=models.CharField(choices=[('stub', 'Stub (Dev/Testing)'), ('deepseek', 'DeepSeek'), ('qwen', 'Qwen (Alibaba)'), ('gemini', 'Gemini (Google)'), ('claude', 'Claude (Anthropic)'), ('chatgpt', 'ChatGPT (OpenAI)')], help_text='Which adapter class to instantiate.', max_length=20),
        ),
    ]
