# Generated by Django 6.0.7 on 2026-07-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_alter_modelinvocation_credits_charged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinvocation',
            name='provider_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Actual wholesale USD cost (computed from real token usage × route wholesale rates).', max_digits=10, null=True),
        ),
    ]
